skinparam dpi 100
skinparam shadowing false
skinparam DefaultFontName Meiryo
skinparam ArrowColor $LineColor
skinparam DefaultFontColor $LineColor
skinparam BackgroundColor transparent

skinparam Activity {
  BorderColor $LineColor
  DiamondBorderColor $LineColor
  BarColor $LineColor
  StartColor $LineColor
  StopColor $LineColor
  BackgroundColor $BackGroundColor
  DiamondBackgroundColor $BackGroundColor
}

skinparam Sequence {
  BorderColor $LineColor
  BackgroundColor $BackGroundColor
  BoxBorderColor $LineColor
  BoxBackgroundColor $BackGroundColor
  DividerBorderColor $LineColor
  DividerBackgroundColor $BackGroundColor
  LifeLineBorderColor $LineColor
  LifeLineBackgroundColor $BackGroundColor
  ReferenceBorderColor $LineColor
  ReferenceBackgroundColor $BackGroundColor
}

skinparam Actor {
  StereotypeFontColor $LineColor
  BorderColor $LineColor
  BackgroundColor $BackGroundColor
}
