!define _Master << (M, Gold) >>
!define _Transaction << (T, DarkSeaGreen) >>
skinparam LineType ortho

legend top left
    凡例
    |= 説明 |= 記号 |
    | 0 or 1 | <$BackGroundBlue> --o\| |
    | 1のみ  | <$BackGroundBlue> --\|\| |
    | 0以上  | <$BackGroundBlue> --o{ |
    | 1以上  | <$BackGroundBlue> --\|{ |
    ----
    M = Master
    T = Transaction
    ----
    ● = 必須項目
    ----
    ※ 各項目は重要なもの以外を省略している
end legend
